<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find sq2_ccv_description)/urdf/common.xacro"/>

  <property name="steering_radius" value="0.01675"/>
  <property name="steering_width" value="0.003"/>
  <property name="steering_mass" value="1.0"/>

  <xacro:macro name="steering" params="prefix parent *joint_origin *joint_axis">
    <joint name="${prefix}_steering_joint" type="revolute">
      <insert_block name="joint_origin"/>
      <parent link="${parent}"/>
      <child link="${prefix}_steering_link"/>
      <insert_block name="joint_axis"/>
	  <limit velocity="6.28" effort="11" lower="${-M_PI/6}" upper="${M_PI/6}"/>
    </joint>

    <link name="${prefix}_steering_link">
      <visual>
		  <origin xyz="0 0 ${steering_width/2}" rpy="0 0 0"/>
        <geometry>
	  	  <cylinder radius="${steering_radius}" length="${steering_width}"/>
        </geometry>
      </visual>
      <collision>
		<origin xyz="0 0 ${steering_width/2}" rpy="0 0 0"/>
        <geometry>
	  	  <cylinder radius="${steering_radius}" length="${steering_width}"/>
        </geometry>
      </collision>
      <inertial>
		<origin xyz="0 0 ${steering_width/2}" rpy="0 0 0"/>
		<cylinder_inertial mass="${steering_mass}" radius="${steering_radius}" length="${steering_width}"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="steering_gazebo" params="prefix">
    <gazebo reference="${prefix}_steering_link">
      <selfCollide>false</selfCollide>
      <mu1 value="0.05"/>
      <mu2 value="0.05"/>
    </gazebo>
  </xacro:macro>

  <!--xacro:macro name="steering_trans" params="prefix">
    <transmission name="${prefix}_steering_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_steering_joint">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_steering_motor">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>30</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro-->

</robot>
