<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find sq2_ccv_description)/urdf/common.xacro"/>

  <property name="lidar_pillar_length" value="0.145"/>
  <property name="lidar_pillar_width" value="0.145"/>
  <property name="lidar_pillar_height" value="0.238"/>
  <property name="lidar_pillar_mass" value="1.0"/>

  <xacro:macro name="lidar_pillar" params="parent *joint_origin">
    <joint name="lidar_pillar_link_joint" type="fixed">
      <insert_block name="joint_origin"/>
      <parent link="${parent}"/>
      <child link="lidar_pillar_link"/>
    </joint>

    <link name="lidar_pillar_link">
      <visual>
		<origin xyz="0.0 0.0 ${lidar_pillar_height/2}" rpy="0 0 0"/>
        <geometry>
		  <box size="${lidar_pillar_length} ${lidar_pillar_width} ${lidar_pillar_height}"/>
        </geometry>
      </visual>
      <collision>
		<origin xyz="0.0 0.0 ${lidar_pillar_height/2}" rpy="0 0 0"/>
        <geometry>
		  <box size="${lidar_pillar_length} ${lidar_pillar_width} ${lidar_pillar_height}"/>
        </geometry>
      </collision>
      <inertial>
		  <origin xyz="0.0 0.0 ${lidar_pillar_height/2}" rpy="0 0 0"/>
        <mass value="5"/>
        <inertia ixx="1" ixy="0" ixz="0" iyz="0" iyy="1" izz="1"/>
      </inertial>
    </link>

  </xacro:macro>

  <xacro:macro name="lidar_pillar_gazebo">
    <gazebo reference="lidar_pillar_link">
      <selfCollide>false</selfCollide>
      <mu1 value="0.05"/>
      <mu2 value="0.05"/>
    </gazebo>

  </xacro:macro>

</robot>
