<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find sq2_ccv_description)/urdf/common.xacro"/>

  <property name="upper_body_length" value="0.258"/>
  <property name="upper_body_width" value="0.258"/>
  <property name="upper_body_height" value="0.508"/>
  <property name="upper_body_mass" value="1.0"/>

  <xacro:macro name="upper_body" params="parent *joint_origin">
    <joint name="upper_body_link_joint" type="fixed">
      <insert_block name="joint_origin"/>
      <parent link="${parent}"/>
      <child link="upper_body_link"/>
    </joint>

    <link name="upper_body_link">
      <visual>
		<origin xyz="0.0 0.0 -${upper_body_height/2}" rpy="0 0 0"/>
        <geometry>
		  <box size="${upper_body_length} ${upper_body_width} ${upper_body_height}"/>
        </geometry>
      </visual>
      <collision>
		<origin xyz="0.0 0.0 -${upper_body_height/2}" rpy="0 0 0"/>
        <geometry>
		  <box size="${upper_body_length} ${upper_body_width} ${upper_body_height}"/>
        </geometry>
      </collision>
      <inertial>
		  <origin xyz="0.0 0.0 ${upper_body_height/2}" rpy="0 0 0"/>
        <mass value="5"/>
        <inertia ixx="1" ixy="0" ixz="0" iyz="0" iyy="1" izz="1"/>
      </inertial>
    </link>

  </xacro:macro>

  <xacro:macro name="upper_body_gazebo">
    <gazebo reference="upper_body_link">
      <selfCollide>false</selfCollide>
      <mu1 value="0.05"/>
      <mu2 value="0.05"/>
    </gazebo>

  </xacro:macro>

</robot>
