sq2_ccv:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  diff_drive_steering_controller:
    type        : "diff_drive_steering_controller/DiffDriveSteeringController"
    left_wheel  : 'left_wheel_joint'
    right_wheel : 'right_wheel_joint'
    left_steering  : 'left_steering_joint'
    right_steering : 'right_steering_joint'
    publish_rate: 50
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.55
    wheel_radius : 0.1435

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 1.0

    # Base frame_id
    base_frame_id: base_footprint #default: base_link

    enable_odom_tf: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 2.5  # m/s
        min_velocity           : -2.5 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.0  # rad/s
        min_velocity           : -1.0
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2
        min_acceleration       : -1.0

    steering_angle_absolute_value_limit: 0.5235987755982988 # M_PI/6 

  roll_pitch_controller:
    type: "sq2_ccv_upper_body_controller/SQ2CCVUpperBodyController"
    roll_joint: 'battery_box_joint'
    roll_axis_reversed: false 
    pitch_joint: 
      - 'front_casters_pitch_joint'
      - 'back_casters_pitch_joint'
    pitch_axis_reversed:
      - false
      - true
    roll_angle_absolute_value_limit  : 0.5235987755982988 
    pitch_angle_absolute_value_limit : 0.5235987755982988 

  turn_table_joint:
    type: effort_controllers/JointVelocityController
    joint: turn_table_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}
