sq2_ccv:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  diff_drive_steering_controller:
    type        : "diff_drive_steering_controller/DiffDriveSteeringController"
    left_wheel  : 'left_wheel_joint'
    right_wheel : 'right_wheel_joint'
    publish_rate: 50
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Wheel separation and diameter. These are both optional.
    # diff_drive_controller will attempt to read either one or both from the
    # URDF if not specified as a parameter
    wheel_separation : 0.55
    wheel_radius : 0.1435

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    wheel_radius_multiplier    : 1.0 # default: 1.0

    # Velocity commands timeout [s], default 0.5
    cmd_vel_timeout: 1.0

    # Base frame_id
    base_frame_id: base_footprint #default: base_link

    enable_odom_tf: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.0  # m/s
        min_velocity           : -1.0 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 1.0  # rad/s
        min_velocity           : -1.0
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2
        min_acceleration       : -1.0

  battery_box_joint:
    type: effort_controllers/JointPositionController
    joint: battery_box_joint
    pid: {p: 1000.0, i: 0.1, d: 100.0}

  right_steering_joint:
    type: effort_controllers/JointPositionController
    joint: right_steering_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  left_steering_joint:
    type: effort_controllers/JointPositionController
    joint: left_steering_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  front_casters_pitch_joint:
    type: effort_controllers/JointPositionController
    joint: front_casters_pitch_joint
    pid: {p: 200.0, i: 0.01, d: 10.0}

  back_casters_pitch_joint:
    type: effort_controllers/JointPositionController
    joint: back_casters_pitch_joint
    pid: {p: 200.0, i: 0.01, d: 10.0}

  turn_table_joint:
    type: effort_controllers/JointVelocityController
    joint: turn_table_joint
    pid: {p: 10.0, i: 0.0, d: 0.0}
